### PR TITLE
Remove circular import risks in Asterix

### PR DESCRIPTION
**Pull request by johanmazoyer**
fixed the circular imports that appear in the `optics` module. 
Solution was to avoid **within the module** broad call to the module, only to part of it
For that reason, within the module `xxx`, we should **not** import with "`from xxx import YYY`" which import all `xxx` package, and prefer `import xxx.yyy as yyy`  and then use `yyy.YYY`, because the second solution does not do a full import of `xxx`

Did the same when necessary to other sub-package at risk (wfsc) to avoid any problems in the future

### CODE REVIEW

**Comment by ivalaginja** [comment]
This looks like it branched off of #66 so I will only look at it once that is merged.

**Comment by ivalaginja** [comment]
@johanmazoyer I see that you did not change this consistently throughout the package, shouldn't that be done? Otherwise we might get circular import warnings in the future, plus our imports are done inconsistently across the package.

**Comment by johanmazoyer** [comment]
Hum I tried to do it constistenly. 
I remove the broad import in the __setup__ of Asterix package, and then clean the function in optics and wfsc. For utils, I think there was no problem

**Comment by ivalaginja** [comment]
I am just afraid that just because there is no problem now, it doesn't mean there won't be one in the future. There are a lot of direct imports of the optics classes, too many to list them all, but some examples:
https://github.com/johanmazoyer/Asterix/blob/eac5efd0f181416630160bba7376c79ed36283cc/Asterix/optics/coronagraph.py#L9
https://github.com/johanmazoyer/Asterix/blob/eac5efd0f181416630160bba7376c79ed36283cc/Asterix/optics/pupil.py#L10
https://github.com/johanmazoyer/Asterix/blob/eac5efd0f181416630160bba7376c79ed36283cc/Asterix/wfsc/wf_control_functions.py#L16
and many more. I feel like it's safer to change them all. Also, consistency will lead people that might not know why sometimes you import the module and sometimes the class directly.

Also, don't forget the noteboo.

**Comment by ivalaginja** [comment]
Ha I was looking at the wrong branches left and right xD Don't mind my previous comment.

**Review by ivalaginja — APPROVED** [review]
Looking ok and fixes the addressed issue.

Note however how this leaves the imports in a fairly inconsistent way across the package:
If I need the class `Pupil`, sometimes it’s imported as `from Asterix.optics import Pupil` now (e.g. in `main_THD.py`) and sometimes as `import Asterix.optics.pupil as pupil` and then call `pupil.Pupil`, like in `coronagraph.py`.
As Johan says, he just removed the subpackage imports within itself.

**Pull request merged**
