### PR TITLE
Use built-in exceptions that are not just `Exception`

### PR DESCRIPTION
**Pull request by ivalaginja**
Replacing all basic exceptions `Exception` with an appropriate built-in exception.

https://docs.python.org/3/library/exceptions.html
https://realpython.com/python-exceptions/

### CODE REVIEW

**Comment by ivalaginja** [comment]
@johanmazoyer what sort of exception are you trying to catch here?
https://github.com/johanmazoyer/Asterix/blob/010acff313f2168988d6d2c84985651a72575818/Asterix/wfsc/wf_sensing_functions.py#L168

**Comment by johanmazoyer** [comment]
> @johanmazoyer what sort of exception are you trying to catch here?
> 
> https://github.com/johanmazoyer/Asterix/blob/010acff313f2168988d6d2c84985651a72575818/Asterix/wfsc/wf_sensing_functions.py#L168

That date back from Axel's core code. I think he's purpose is to throw a warning when the SVD do not work, not an exception per se. Maybe we should ask him directly what his purpose is to clarify,

**Comment by ivalaginja** [comment]
Catching an exception here makes absolutely sense, I am just trying to refine it to only catch the exceptions we are willing to catch. I can probably test this and figure it out, but if you remember what the exception was that happened here @axelpotier-astro that'd be great.

**Comment by ivalaginja** [comment]
I put this here now: https://github.com/johanmazoyer/Asterix/issues/91
as it is not high priority.

**Review by johanmazoyer — APPROVED** [review]

**Pull request merged**
