### PR TITLE
Create tutorial notebook

### PR DESCRIPTION
**Pull request by ivalaginja**
- I took the existing tutorial in form of a script `tuto_asterix_model.py` [here](https://github.com/johanmazoyer/Asterix/blob/94c53ed370d66e138b3fe526693eb11709d2710d/Asterix/tuto_asterix_model.py) and created a notebook version of it.
- I fixed up the scripted tutorial itself
- I made the file output in the phase generation function temporary - I think it's useful to be able to simulate things without having to worry about file I/O.
- I added a pytest for the perfect coronagraph, which is the default in the example configuration file

### CODE REVIEW

**Review by johanmazoyer — APPROVED** [review]
ok, by me. I'm fine with the change in the save init phase. If I understood correctly the behavior is still saved all the times except if no directory is provided ?

**Comment by ivalaginja** [comment]
@johanmazoyer this was a **Draft** PR!!!

**Comment by ivalaginja** [comment]
I wasn't ready yet to have this merged :/

**Comment by ivalaginja** [comment]
I think I didn't have much left, I can do a mini-PR to add the last changes I wanted to add, it will be fine. But can we leave Draft PRs alone in the future? 😬 I never clean those out as I would for a PR that is ready to be reviewed and merged.

**Pull request merged**
